version: "3.5"

services:
 frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5000:80"
    networks:
     - app-network

 backend:
   container_name: backend
   build: ./backend
   ports:
     - "8080:8080"
   environment:
     POSTGRES_HOST: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DATABASE: postgres
   networks:
     - app-network
 db:
   container_name: postgres_sql
   image: postgres:latest
   ports:
     - "5432:5432"
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
       POSTGRES_HOST: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DATABASE: postgres
   networks:
     - app-network




networks:
  app-network:

volumes:
  db-data:





