version: '3.8'

services:
  db:
    container_name: postgres_sql
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres  # Corrected the variable name
    networks:
      - app-network

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db  # Should match the service name, not 'postgres'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: fullstack-docker-project_app-network

volumes:
  db-data:
    name: fullstack-docker-project_db-data


