services:
 frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:80"
    networks:
     - app-network
    depends_on:
      - backend

 backend:
   container_name: backend
   build: ./backend
   ports:
     - "8080:8080"
   environment:
     POSTGRES_HOST: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DATABASE: postgres
   networks:
     - app-network
   depends_on:
     - db
 db:
   container_name: postgres_sql
   image: "postgres:9.6-alpine"
   ports:
     - "5432:5432"
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
       POSTGRES_HOST: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DATABASE: postgres
   networks:
     - app-network





networks:
  app-network:
    name: fullstack-docker-project_app-network
volumes:
  db-data:
    name: fullstack-docker-project_db-data

